amekes <- auk_ebd("/Users/archith/Downloads/ebd_US_amekes_smp_relApr-2024/ebd_US_amekes_smp_relApr-2024.txt", "/Users/archith/Downloads/ebd_US_amekes_smp_relApr-2024/ebd_US_amekes_smp_relApr-2024_sampling.txt")
amekes <- auk_complete(amekes)
amekes <- auk_date(amekes, date = c("*-06-01", "*-06-30"))
amekes <- auk_state(amekes, c("US-DC", "US-NY", "US-PA", "US-CT", "US-DE", "US-FL", "US-GA", "US-ME", "US-MD", "US-MA", "US-NH", "US-NJ", "US-NC", "US-RI", "US-SC", "US-VT", "US-VA", "US-WV"))
#amekes <- auk_state(amekes, "US-FL")
#amekes <- auk_distance(amekes, distance = c(0,10))
#amekes <- auk_bcr(amekes, c(16))
auk_filter(amekes, "/Users/archith/Downloads/amekes_FILTERED.txt", "/Users/archith/Downloads/amekes_FILTERED_SAMPLING.txt", overwrite = TRUE)
sampling <- read_sampling("/Users/archith/Downloads/amekes_FILTERED_SAMPLING.txt")
kestrels <- read_ebd("/Users/archith/Downloads/amekes_FILTERED.txt")
